global:
  scrape_interval: 15s

scrape_configs:
  - job_name: app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]

  - job_name: mysqld-exporter
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: redis-exporter
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: statsd-exporter
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  - job_name: alloy
    static_configs:
      - targets: ["alloy:12345"]
